notemp: true
local-cores: 6
latency-wait: 180
max-jobs-per-second: 10
keep-going: true
resources: 'network_connections=3'
default-resources:
  - 'pmem=8192'
  - 'disk_mb=100000'
  - 'walltime_hr=0'
  - 'walltime_min=29'
  - 'walltime_sec=59'
  - 'gpu_mem_mb=1000'
  - 'outdir="log/"'
use-conda: true
conda-frontend: 'mamba'
conda-prefix: '/pollard/home/bsmith/.snakemake/conda'
use-singularity: true
singularity-args: "--bind /pollard/ --nv --bind /salilab/diva1/home/anaconda/anaconda3 --bind /wynton/home/pollard/bsmith"
singularity-prefix: "/pollard/home/bsmith/.snakemake/singularity"
config: ['MAX_THREADS=24', 'USE_CUDA=1']
jobscript: 'profiles/wynton-qsub-gpu/jobscript.sh'
drmaa: " -cwd \
        -v PATH \
        -pe smp {threads} \
        -l h_rt={resources.walltime_hr}:{resources.walltime_min}:{resources.walltime_sec} \
        -l mem_free={resources.pmem}M \
        -o {resources.outdir} \
        -q gpu.q -l gpu_mem={resources.gpu_mem_mb}M \
        -j yes \
        -terse \
        "
jobname: '{name}.{jobid}.snkjb'
