notemp: true
local-cores: 6
latency-wait: 180
max-jobs-per-second: 10
keep-going: true
printshellcmds: true
resources: 'network_connections=3'
default-resources:
  - 'pmem=8192'
  - 'disk_mb=100000'
  - 'walltime_hr=0'
  - 'walltime_min=29'
  - 'walltime_sec=59'
  - 'outdir="log/"'
  - 'device="cpu"'
use-conda: true
conda-frontend: 'mamba'
conda-prefix: '/wynton/home/pollard/bsmith/.snakemake/conda'
use-singularity: true
singularity-prefix: "/wynton/home/pollard/bsmith/.snakemake/singularity"
singularity-args: "--bind /pollard/ --bind /salilab/diva1/home/anaconda/anaconda3 --bind /wynton/home/pollard/bsmith"
config: ['MAX_THREADS=24', 'USE_CUDA=0']
jobscript: 'profiles/wynton-qsub/jobscript.sh'
cluster: "qsub -cwd \
        -v PATH \
        -pe smp {threads} \
        -l h_rt={resources.walltime_hr}:{resources.walltime_min}:{resources.walltime_sec} \
        -l mem_free={resources.pmem}M \
        -j yes \
        -terse \
        -o {resources.outdir} \
        "
jobname: '{name}.{jobid}.snkjb'
